export const RULE_CONFIG = {
  BRAND_NAME_FUZZY_THRESHOLD: 0.93,
  CLASS_TYPE_FUZZY_THRESHOLD: 0.90,
  BOTTLER_FUZZY_THRESHOLD: 0.80,
  WARNING_TEXT_FUZZY_THRESHOLD: 0.95,
  ABV_TOLERANCE: 0.1,
  NET_CONTENTS_TOLERANCE_ML: 1,
  MAX_UPLOAD_BYTES: 25 * 1024 * 1024,
  ALLOWED_MIME_TYPES: ['image/png', 'image/jpeg', 'image/jpg', 'application/pdf'],
};
